token:
  header: Authorization
  schema: Bearer
  secretKey: banyuan
  expireSec: 3600

server:
  port: 8088


# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
spring:
  profiles:
    active: @spring.profiles.active@
